version: '3.8'

services:
  scraper:
    build: .
    env_file:
      - .env
    volumes:
      - ./html_files:/app/html_files
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - arambyeol-network

networks:
  arambyeol-network:
    external: true
